services:
  db:
    image: postgres:16-alpine
    container_name: masterthpt-db
    restart: unless-stopped
    env_file:
      - ./.env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: