from typing import Literal, Optional, TypedDict, Annotated, Any, List
from langgraph.graph.message import add_messages

from master.agents.common.message import MessageRequest, MessageResponse
from master.agents.common.learner_profile import LearnerProfile
from master.agents.common.message import ExamQuestion, StudentAnswer
from master.common.message import GradeResult, Solution

class AgentState(TypedDict):
    # Request
    request: MessageRequest
    phase: Literal["tools", "draft", "verify", "END"]

    # Learner context
    learner_profile: LearnerProfile # BKT mastery per KC, IRT theta, history

    # Exam context
    exam_id: Optional[str]
    questions: list[ExamQuestion]
    student_answers: list[StudentAnswer]

    # Debate context
    round: int
    max_round: int
    is_agreed: List[bool]
    phase: Literal["draft", "debate", "verify", "finalize"]
    reasoning: str
    confidence: List[float] # confidence per question                    
    teacher_feedback: Annotated[List[Any], add_messages]
    verifier_feedback: Annotated[List[Any], add_messages]

    # Grading result
    grade_result: Optional[GradeResult]

    # Lời giải
    solutions: Optional[list[Solution]] # Solutions generated by TeacherAgent
    verified_solutions: Optional[list[Solution]] # Solutions verified by VerifierAgent

    # Adaptive
    selected_questions: Optional[list[ExamQuestion]]
    profile_updates: Optional[dict]
    discrimination_a: Optional[list[float]]
    difficulty_b: Optional[list[float]]

    # Response
    response: Optional[List[MessageResponse]] = None