from typing import Literal, Optional, TypedDict
from message import MessageRequest, MessageResponse
from learner_profile import LearnerProfile
from master.agents.common.message import ExamQuestion, StudentAnswer
from master.agents.teacher import Output
from master.common.message import GradeResult, Solution

class AgentState(TypedDict):
    # Request
    request: MessageRequest
    # intent: Intent

    # Learner context
    # student_id: Optional[str]
    # session_id: Optional[str]
    learner_profile: LearnerProfile # BKT mastery per KC, IRT theta, history

    # Exam context
    exam_id: Optional[str]
    questions: list[ExamQuestion]
    student_answers: list[StudentAnswer]
    raw_request: MessageRequest             # Toàn bộ request gốc

    # Debate context
    round: int
    max_round: int
    phase: Literal["draft", "debate", "verify", "finalize"]
    debate_outputs: list[Output]

    # Grading result - Điểm được chấm từ phía /app gửi về (điểm, câu đúng, câu sai)
    grade_result: Optional[GradeResult]

    # Lời giải
    solutions: Optional[list[Solution]] # Solutions generated by TeacherAgent
    verified_solutions: Optional[list[Solution]] # Solutions verified by VerifierAgent

    # Adaptive
    selected_questions: Optional[list[ExamQuestion]]
    profile_updates: Optional[dict]

    # Response
    response: Optional[MessageResponse]